const router = require('express').Router()
const administrationController = require('../controllers/administration_controller')
const validatorMiddleware = require('../middlewares/validation_middleware')
const authMiddleware = require('../middlewares/auth_middleware')
const multerConfig = require('../config/multer_config')

router.get('/', authMiddleware.loggedIn, administrationController.showHomePage)
router.get('/profile', authMiddleware.loggedIn, administrationController.showProfilePage)
router.post('/profile-update', authMiddleware.loggedIn, multerConfig.single('avatar'), administrationController.profileUpdate)
router.get('/movies', authMiddleware.loggedIn, administrationController.showMoviesPage)
router.post('/movies', authMiddleware.loggedIn, validatorMiddleware.validateNewMovie(), administrationController.saveMovies)
router.get('/my-movies', authMiddleware.loggedIn, administrationController.showMyMovies)
router.get('/removeMyMovies/:_id', authMiddleware.loggedIn, administrationController.removeMyMovies)
router.get('/books', authMiddleware.loggedIn, administrationController.showBooksPage)
router.post('/books', authMiddleware.loggedIn, validatorMiddleware.validateNewBook(), administrationController.saveBooks)
router.get('/my-books', authMiddleware.loggedIn, administrationController.showMyBooks)
router.get('/removeMyBooks/:_id', authMiddleware.loggedIn, administrationController.removeMyBooks)
router.get('/days', authMiddleware.loggedIn, administrationController.showDaysPage)
router.post('/days', authMiddleware.loggedIn, validatorMiddleware.validateNewSpecialDay(), administrationController.saveDays)
router.get('/my-days', authMiddleware.loggedIn, administrationController.showMyDays)
router.get('/removeMyDays/:_id', authMiddleware.loggedIn, administrationController.removeMyDays)
router.get('/persons', authMiddleware.loggedIn, administrationController.showPersonsPage)
router.post('/persons', authMiddleware.loggedIn, validatorMiddleware.validateNewPerson(), administrationController.savePersons)
router.get('/my-persons', authMiddleware.loggedIn, administrationController.showMyPersons)
router.get('/removeMyPersons/:_id', authMiddleware.loggedIn, administrationController.removeMyPersons)
router.get('/anythings', authMiddleware.loggedIn, administrationController.showAnythingsPage)
router.post('/anythings', authMiddleware.loggedIn, administrationController.saveAnythings)
router.get('/my-anythings', authMiddleware.loggedIn, administrationController.showMyAnythings)
router.get('/removeMyAnythings/:_id', authMiddleware.loggedIn, administrationController.removeMyAnythings)
router.get('/offers', authMiddleware.loggedIn, administrationController.showOffersPage)
router.post('/offers', authMiddleware.loggedIn, administrationController.saveOffers)

module.exports = router;